"""Initial revision

Revision ID: 3bd06dab86d7
Revises:
Create Date: 2025-05-04 23:47:52.539910

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bd06dab86d7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("about_me", sa.String(length=300), nullable=True),
        sa.Column("age", sa.SmallInteger(), nullable=False),
        sa.Column("city", sa.String(length=50), nullable=False),
        sa.Column(
            "sex",
            sa.Enum("male", "female", "unspecified", name="sexenumdb"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("telegram_id"),
    )
    op.create_table(
        "user_preferences",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "sex",
            sa.Enum("male", "female", "unspecified", name="sexenumdb"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["telegram_id"], ["user_profiles.telegram_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("telegram_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_preferences")
    op.drop_table("user_profiles")
    op.execute("DROP TYPE sexenumdb;")
    # ### end Alembic commands ###
